### ISSUE TITLE
want to type part of a folder name instead

### ISSUE THREAD

**Issue by knurd** [hartag/keynav#4]
The [TB page for this extension](https://addons.thunderbird.net/en-GB/thunderbird/addon/quick-folder-key-navigation/) states "This extension makes it possible to quickly navigate to a particular folder in the folder pane simply by typing the *first few letters* of the folder name", but the readme here on github says "to be quickly navigated by typing *part* or all of a folder name". Is that a bug in the readme or is there a way to enable the "type part of a folder name" function somehow, as that's exactly what I'm looking for.

**Comment by hartag** [comment]
Hi. If by "part of a folder name" you mean that you want to type a portion of the folder name but not starting witht he first letter, for example, you want to use "comm" to search for a folder called "private communications" rather than using something like "priv", then you are right. Now that you've brought it to my attention, the description on the TB page is clearer about what the add-on does. The way I wrote it in the readme file suggests that you can type any part of the folder name and it will match on it.

The add-on is not that sophistocated. It is taking advantage of a function of the tree widget used to display the mail folder tree that allows the mail folder tree itself to respond directly to key presses when it has the focus. As such, it essentially searches via first-letter navigation but if you type at a reasonable rate, it accumulates all the letters you type and uses the entire sequence of characters to match the beginning of the folder name. It resets and forgets what you've typed after a short lapse in time (I'm guessing around 0.25 to 0.5 seconds).

Does this answer your question? If so, then I should update the GitHub readme to make this more clear.

**Comment by knurd** [comment]
> you want to use "comm" to search for a folder called "private communications" rather than using something like "priv"

Yup. And I assume that's not possible with the tree widget? Well, I guess in that case I have to live with that. :-/ 

But yeah, guess updating the readme would be good, but no pressure, I guess only a few lost souls like myself will find and read it. :-D

**Comment by jobisoft** [comment]
The current concept of the add-on will not work in Thunderbird 115, because a big chunk of core code has been rewritten and removed and what this add-on did is no longer supported. However, I did try to re-create the functionality in a pure WebExtension way and filed Pull Request #6 .

I hope the maintainer accepts this. I think the new version does what you had in mind:
[keynav_4_0.zip](https://github.com/hartag/keynav/files/12196884/keynav_4_0.zip)

**Comment by ftoledo** [comment]
I just found that this addon work again at my TB 115.11.1 
 I have several newsgroups that have folders like this capture:

![imagen](https://github.com/hartag/keynav/assets/95441/8fe7783d-d840-4452-8e54-0fc70899fed2)

I cannot search for "console" 

![imagen](https://github.com/hartag/keynav/assets/95441/d8b75d22-92fc-4af3-8d57-2aed8ca9c0e5)

it's work sif i use "retronet.rtn_conso"
support to search similar to sql LIKE '%text%' will very nice.

thanks!

**Comment by hartag** [comment]
The ability to match on text anywhere in the folder name has been added to the add-on.
